### ISSUE TITLE
Task: Actualizar ponentes

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#21]
# description
En la sección Ponentes se debe de actualizar la información de los ponentes de esta edición

Los asignados deberán seleccionar 2 de los ponentes y añadir una breve introducción a los mismos así como enlaces a sus redes, github ...

## programa
[20211022_Horario_Innosoft_21.pdf](https://github.com/JSnow11/web/files/7412363/20211022_Horario_Innosoft_21.pdf)
## ponentes
https://docs.google.com/document/d/142lgskJBuwgicgIlB9usHhAZzjXx37Vwj6P4US3ZQ8U/edit?usp=sharing

# to-do
 - [x] #22
 - [x] #23 (sputnik, mirar comentario en este issue)
 - [x] #24
 - [x] #25
 - [x] #26
 - [x] #27
 - [x] #28
 - [x] #29
 - [x] #33
 - [x] #34
 - [x] #35
 - [x] #36
 - [x] #37
 - [x] #38
 - [x] #39
 - [x] #31
 - [x] #30
 - [x] #32
 - [x] #52
 - [x] revisar erratas y descripciones

# accept
- [x] Los ponentes están actualizados
- [x] no hay erratas

**Comment by JSnow11** [comment]
# feedback
**lizseth — hoy a las 17:07**

Buenas chicos, soy de programa, hay erraras
en las charlas con los nombres de los ponentes
y en las biografías que habeís puesto, las hemos pasado con fotos
hay un ponente, **David Sanchez** que nos ha pedido que pongais su logo
su empresa es **sputnik** ciberseguridad
