### ISSUE TITLE
Task: añadir Alberto Martín a introducción al hacking

### ISSUE THREAD

**Issue by JSnow11** [JSnow11/web#59]
# description
Primera tarea, añadir al taller de Introduccion al hacking a alberto martin como ayudante

# to-do
- [x] añadir ayudante a ponentes
- [x] añadir ayudante a la ponencia 

# accept
- [x] ayudante visible en la ponencia y en ponentes
